// Run from any directory. Only teach/source-data.js is written.
import { readFile, readdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { createHash } from "node:crypto";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.dirname(here);
async function list(directory) {
  const entries = await readdir(path.join(root, directory), { withFileTypes: true });
  const groups = await Promise.all(entries.map((entry) => {
    const relative = `${directory}/${entry.name}`;
    return entry.isDirectory() ? list(relative) : /\.(ts|mjs|html|css)$/.test(entry.name) ? [relative] : [];
  }));
  return groups.flat();
}
const paths = ["package.json", "public/manifest.json", "public/options.html", "tsconfig.json", "vitest.config.ts", "playwright.config.ts", ...(await Promise.all(["src", "test", "e2e", "scripts"].map(list))).flat()].sort();
const files = {};
for (const name of paths) {
  const text = await readFile(path.join(root, name), "utf8");
  files[name] = { text, sha256: createHash("sha256").update(text).digest("hex") };
}
const snapshot = { capturedAt: new Date().toISOString(), files };
await writeFile(path.join(here, "source-data.js"), `// Generated by update-sources.mjs. A read-only snapshot of the working tree.\nwindow.TEACH_SOURCES = ${JSON.stringify(snapshot)};\n`);
console.log(`Captured ${paths.length} source files into teach/source-data.js`);
